version: '3'

services: 
    cookiecutter:
        build:
            context: .
            args: 
                repo: ${TEMPLATE_REPO_URL}
                full_name: ${full_name}
                email: ${email}
                github_username: "${GITHUB_USERNAME}"
                app_name: "${APP_NAME}"
                project_short_description: "${PROJECT_SHORT_DESCRIPTION}"
                project_name: "${PROJECT_NAME}"
        image: ${DOCKER_USERNAME}/cookiecutter:initiator
        container_name: flask-sql-ci-initiator
        command: tail -f /dev/null
